# Site settings
title: Arslan Ali
description: A personal webpage of Arslan Ali
#baseurl: "/marslanali" #/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Arslan Ali
user_description: 
                Software Engineer with a demonstrated history of working in the industry and specializing in the C++ object-oriented design and development arena.
                Skilled in C/C++, Python, UNIX/Linux, Bash Scripting, and Git. Strong engineering professional with a Bachelors of Engineering, and worked as a
                Graduate Research at the Korea University of Technology & Education, South Korea.


user_title: Software Engineer @ Afiniti
email: marslanali800@gmail.com
twitter_username: marslanali800
github_username:  marslanali
gplus_username:  marslanali800

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
