# Site settings
title: Arslan Ali
description: A personal webpage of Arslan Ali
#baseurl: "/marslanali" #/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Arslan Ali
user_description1:

user_description2:
              I'm Arslan Ali working mainly in C++ & Linux. I design, build, and maintain efficient, reusable,
              and reliable C/C++ codes. I am well acquainted with code review, refactoring, testing, maintaining,
              and writing excellent documentation. I also have a strong passion for AI & Machine Learning.

user_description3:
              Previously, I've worked as a Graduate Research at Korea University of Technology & Education,
              South Korea, with interests lies in Machine Learning & Teleoperation. I worked with C++ and
              Python development with Linux, Robot Operating System (ROS), and high-performance physics engines
              for simulations, i.e., gazebo. I also had worked with Unity, OpenGL, and Windows Desktop Application
              development using C++ & MFC.



user_title: Software Development Consultant
email: marslanali800@gmail.com
twitter_username: marslanali800
github_username:  marslanali
gplus_username:  marslanali800

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
